# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'idealista_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'idealista_analytics'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  idealista_analytics:
    # Config indicated by + and applies to all files under models/
    +materialized: view
    +dbt-osmosis: "{model}.yml"
    
    base:
      +materialized: view
      +schema: dbt_base
    
    staging:
      +materialized: table
      +schema: dbt_staging
    
    intermediate:
      +materialized: table
      +schema: dbt_intermediate
    
    mart:
      +materialized: table
      +schema: dbt_mart

# Seeds configuration
seeds:
  idealista_analytics:
    +schema: dbt_seed

# Snapshots configuration
snapshots:
  idealista_analytics:
    +target_schema: dbt_snapshots
    +strategy: timestamp
    +updated_at: updated_at
